apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-insights-backend
  namespace: mimir-insights
  labels:
    app: mimir-insights-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir-insights-backend
  template:
    metadata:
      labels:
        app: mimir-insights-backend
    spec:
      containers:
      - name: mimir-insights-backend
        image: mimir-insights-backend:fast-1752813464
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MIMIR_NAMESPACE
          value: "auto"
        - name: MIMIR_API_URL
          value: "auto"
        - name: LOG_LEVEL
          value: "info"
        - name: K8S_IN_CLUSTER
          value: "true"
        - name: MIMIR_AUTO_DISCOVER
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-insights-backend
  namespace: mimir-insights
  labels:
    app: mimir-insights-backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: mimir-insights-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-insights-frontend
  namespace: mimir-insights
  labels:
    app: mimir-insights-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir-insights-frontend
  template:
    metadata:
      labels:
        app: mimir-insights-frontend
    spec:
      containers:
      - name: mimir-insights-frontend
        image: mimir-insights-frontend:fast-1752813464
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 20m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-insights-frontend
  namespace: mimir-insights
  labels:
    app: mimir-insights-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: mimir-insights-frontend 