---
# Mimir Services
# Services for all Mimir components

apiVersion: v1
kind: Service
metadata:
  name: mimir-distributor
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-distributor
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/component: distributor
spec:
  selector:
    app.kubernetes.io/name: mimir-distributor
  ports:
  - name: http-metrics
    port: 9009
    targetPort: 9009
  - name: grpc
    port: 9095
    targetPort: 9095
  - name: memberlist
    port: 7946
    targetPort: 7946
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-ingester
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-ingester
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/component: ingester
spec:
  selector:
    app.kubernetes.io/name: mimir-ingester
  ports:
  - name: http-metrics
    port: 9009
    targetPort: 9009
  - name: grpc
    port: 9095
    targetPort: 9095
  - name: memberlist
    port: 7946
    targetPort: 7946
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-querier
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-querier
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/component: querier
spec:
  selector:
    app.kubernetes.io/name: mimir-querier
  ports:
  - name: http-metrics
    port: 9009
    targetPort: 9009
  - name: grpc
    port: 9095
    targetPort: 9095
  - name: memberlist
    port: 7946
    targetPort: 7946
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-compactor
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-compactor
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/component: compactor
spec:
  selector:
    app.kubernetes.io/name: mimir-compactor
  ports:
  - name: http-metrics
    port: 9009
    targetPort: 9009
  - name: memberlist
    port: 7946
    targetPort: 7946
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-ruler
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-ruler
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/component: ruler
spec:
  selector:
    app.kubernetes.io/name: mimir-ruler
  ports:
  - name: http-metrics
    port: 9009
    targetPort: 9009
  - name: memberlist
    port: 7946
    targetPort: 7946
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-alertmanager
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-alertmanager
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/component: alertmanager
spec:
  selector:
    app.kubernetes.io/name: mimir-alertmanager
  ports:
  - name: http-metrics
    port: 9009
    targetPort: 9009
  - name: memberlist
    port: 7946
    targetPort: 7946
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-store-gateway
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-store-gateway
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/component: store-gateway
spec:
  selector:
    app.kubernetes.io/name: mimir-store-gateway
  ports:
  - name: http-metrics
    port: 9009
    targetPort: 9009
  - name: grpc
    port: 9095
    targetPort: 9095
  - name: memberlist
    port: 7946
    targetPort: 7946
---
# External service for Mimir API access
apiVersion: v1
kind: Service
metadata:
  name: mimir-api
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-api
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: mimir-querier
  ports:
  - name: http
    port: 9009
    targetPort: 9009
  - name: grpc
    port: 9095
    targetPort: 9095
---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mimir-ingress
  namespace: mimir
  labels:
    app.kubernetes.io/name: mimir-ingress
    app.kubernetes.io/part-of: mimir
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: mimir.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mimir-api
            port:
              number: 9009 