apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alloy-statefulset
  namespace: test-alloy-statefulset
  labels:
    app.kubernetes.io/name: alloy
    component: monitoring
spec:
  serviceName: alloy
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alloy
    spec:
      containers:
      - name: alloy
        image: grafana/alloy:v1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy-daemonset
  namespace: test-alloy-statefulset
  labels:
    app.kubernetes.io/name: alloy
    type: daemonset
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alloy
    spec:
      containers:
      - name: alloy
        image: grafana/alloy:v1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
