server:
  port: "8080"
  host: "0.0.0.0"

mimir:
  namespace: "mimir"
  api_url: "http://mimir-distributor:9090"
  timeout: 30

k8s:
  cluster_url: ""
  in_cluster: true
  config_path: ""
  tenant_label: "team"
  tenant_prefix: "tenant-"

log:
  level: "info"
  format: "json"

ui:
  theme: "dark"
  refresh_interval: 30

llm:
  enabled: false
  provider: "openai"
  api_key: ""
  endpoint: ""
  model: "gpt-4"
  max_tokens: 1000 