{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mimir-insights.fullname" . }}-frontend
  namespace: {{ include "mimir-insights.namespace" . }}
  labels:
    {{- include "mimir-insights.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "mimir-insights.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "mimir-insights.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.frontend.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ if kindIs "map" .Values.frontend.image }}{{ if .Values.global.imageRegistry }}{{ .Values.global.imageRegistry }}/{{ .Values.frontend.image.repository }}{{ else }}{{ .Values.frontend.image.repository }}{{ end }}:{{ .Values.frontend.image.tag }}{{ else }}{{ .Values.frontend.image }}{{ end }}
          imagePullPolicy: {{ if kindIs "map" .Values.frontend.image }}{{ .Values.frontend.image.pullPolicy | default "IfNotPresent" }}{{ else }}IfNotPresent{{ end }}
          {{- if .Values.frontend.env }}
          env:
            {{- range .Values.frontend.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config/config.js
              subPath: config.js
              readOnly: true
            - name: frontend-config-root
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
            - name: frontend-config-dynamic
              mountPath: /usr/share/nginx/html/dynamic-config.js
              subPath: config.js
              readOnly: true
            - name: nginx-tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- if .Values.frontend.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          {{- end }}
      volumes:
        - name: frontend-config
          configMap:
            name: {{ include "mimir-insights.fullname" . }}-frontend-config
        - name: frontend-config-root
          configMap:
            name: {{ include "mimir-insights.fullname" . }}-frontend-config
        - name: frontend-config-dynamic
          configMap:
            name: {{ include "mimir-insights.fullname" . }}-frontend-config
        - name: nginx-tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 