[object Object]{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mimir-insights.fullname . }}
  namespace: {{ includemimir-insights.namespace" . }}
  labels:
    {{- includemimir-insights.labels" . | nindent4  {{- with .Values.ingress.annotations }}
  annotations:
  [object Object]{- toYaml . | nindent 4
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
[object Object]{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  [object Object]{- range .Values.ingress.tls }}
    - hosts:
    [object Object]{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  [object Object]{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        [object Object]{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
            [object Object]{- if .backend.service }}
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {[object Object] .backend.service.port.number }}
            [object Object]{- end }}
        {{- end }}
  {{- end }}
{{- end }} 